### ISSUE TITLE
请问能不能解释一下3个apk之间有什么区别呢?

### ISSUE THREAD

**Issue by YoonaLimSauce** [eddlez/litiaotiao_package_backup#13]
才了解到李跳跳这款软件
想学习使用一下
请问一下仓库里面的三个apk之间有什么功能区别吗?

**Comment by eddlez** [comment]
更新了下README，里面写了3个APK的功能
只是用李跳跳的话，第一个就行
当初还没取消分享的时候，作者的网盘里分享了三个APK，当时只是想着简单备份下，就把三个APK全上传了
