### ISSUE TITLE
请问其他两个APP，是有其他功能么

### ISSUE THREAD

**Issue by k-user** [eddlez/litiaotiao_package_backup#6]

**Comment by eddlez** [comment]
好像派大星版是李跳跳的一个测试版本，真实好友是用来检测微信好友是否删除你了，不过这两个应用我没用过
如果只是想使用李跳跳，应该只用下载正式版就行，不用管另外两个

**Comment by Yonggie** [comment]
> 好像派大星版是李跳跳的一个测试版本，真实好友是用来检测微信好友是否删除你了，不过这两个应用我都没用过 如果只是想使用李跳跳，只用下载正式版就行，不用管另外两个

正式版安装出来是 派大星2.2啊

**Comment by eddlez** [comment]
> 正式版安装出来是 派大星2.2啊

确实哦，之前没注意到正式版的版本号，那估计派大星2.07版本的就是之前的一个旧版本吧

**Comment by k-user** [comment]
好的那我就只用李跳跳啦，感谢回答
